dist: xenial

language: java
jdk:
 - oraclejdk11
 - openjdk11

before_install:
 - chmod +x mvnw

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - cp .travis.settings.xml $HOME/.m2/settings.xml
 - mvn deploy

#deploy:
# provider: script
# script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
# on:
#  all_branches: true

script:
 - mvn test
